version: "3"

services:
  db:
    image: postgres
    container_name: for_postgres
    restart: always
    environment:
      - POSTGRES_DB=psql_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - order-product

  app:
    container_name: for_django
    build:
      dockerfile: Dockerfile
      context: .
#    command:
#      - python manage.py runserver 0.0.0.0:8000
    volumes:
      - /usr/src/app/django
    depends_on:
      - db
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    networks:
      - order-product
#    command: python manage.py runserver

networks:
  order-product: